version: '3.4'

services:

  myfamilymanager-api:
    image: myfamilymanager-api
    container_name: myfamilymanager-api
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      DefaultConnection: local
    build:
      context: .
      dockerfile: Services/Core/MyFamilyManager.API/Dockerfile.heroku
  
  myfamilymanager-identity:
    image: myfamilymanager-identity
    container_name: myfamilymanager-identity
    environment:
      ASPNETCORE_ENVIRONMENT: Production
    build:
      context: .
      dockerfile: Services/Identity/MyFamilyManager.Identity.API/Dockerfile.heroku

  myfamilymanager-web:
    image: myfamilymanager-web
    container_name: myfamilymanager-web
    environment:
      ASPNETCORE_ENVIRONMENT: Production
    build:
      context: .
      dockerfile: Web/MyFamilyManager.Web/Dockerfile.heroku