version: '3.4'

services:

  myfamilymanager-web:
    image: myfamilymanager-web
    container_name: myfamilymanager-web
    build:
      context: .
      dockerfile: Services/Core/MyFamilyManager.API/Dockerfile.heroku