version: '3.4'

services:

  myfamilymanager-web:
    image: registry.heroku.com/myfamilymanager-web/web
    container_name: registry.heroku.com/myfamilymanager-web/web
    build:
      context: .
      dockerfile: Services/Core/MyFamilyManager.API/Dockerfile.heroku