name: CI

on: 
  push:
    branches: 
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build #set the whatever name you want to this step
      id: heroku
      run: docker build . --file /src/Services/Core/MyFamilyManager.API/Dockerfile --tag registry.heroku.com/myfamilymanager-web/web
    - name: Push
      run: docker push registry.heroku.com/myfamilymanager-web/web
    - name: Release
      run: heroku container:release web --app myfamilymanager-web
