name: Test1

on: 
  push:
    branches: 
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build
      run: docker-compose -f ./src/docker-compose.heroku.yml build
    - name: login
      run: echo ${{ secrets.HEROKU_API_KEY }} | docker login --username=${{ secrets.HEROKU_EMAIL }} registry.heroku.com --password-stdin
    - name: create credentialfile
      run: |
      cat >~/.netrc <<EOF 
        machine api.heroku.com
        login ${{ secrets.HEROKU_EMAIL }}
        password ${{ secrets.HEROKU_API_KEY }}
        EOF
    - name: TagImage
      run: docker tag myfamilymanager-web registry.heroku.com/myfamilymanager-web/web
   # - name: Build #set the whatever name you want to this step
   #   id: heroku
   #   run: docker build . --file src/Services/Core/MyFamilyManager.API/Dockerfile --tag registry.heroku.com/myfamilymanager-web/web
    - name: Push
      run: docker push registry.heroku.com/myfamilymanager-web/web
    - name: Release
      run: heroku container:release web --app myfamilymanager-web
